[package]
name = "rust_sdl2_demos"
version = "0.1.0"
authors = ["enerqi <enerqi@enerqi>"]
build = "build.rs"

[dependencies]
maplit = "0.1.2"
num = "*"
sdl2 = "0.14.0"
sdl2_ttf = "0.14.0"
sdl2_image = "1.0.0"
