[package]
name = "rust_sdl2_demos"
version = "0.1.0"
authors = ["enerqi <enerqi@enerqi>"]
build = "build.rs"

[dependencies]
image = "*"
maplit = "0.1.2"
num = "*"
sdl2 = "^0.18.0"
sdl2_image = "^0.18.0"
sdl2_ttf = "^0.16.2"
sdl2-sys = "0.8.1"
